apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-wzdemo
  name: svc-wzdemo
  namespace: deftones
spec:
  ports:
  - name: wzdemo
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wzdemo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---

apiVersion: v1
data:
  demo.conf: "{{.global.cpu.max}}/{{.idc.mem.max}}/{{.secret.aaabccc}}"
kind: ConfigMap
metadata:
  name: cm-wzdemo
  namespace: deftones

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wzdemo
  name: wzdemo-server
  namespace: deftones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wzdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: wzdemo
    spec:
      containers:
        - image: 'reg.qiniu.com/fun/callisto:{{.idc.version}}'
          imagePullPolicy: Always
          name: demo-0
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 333m
              memory: 1Gi
          volumeMounts:
            - mountPath: /go/src/demo.conf
              name: cm-wzdemo
              subPath: demo.conf
      volumes:
        - configMap:
            items:
              - key: demo.conf
                path: demo.conf
            name: cm-wzdemo
          name: cm-wzdemo

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: public
  generation: 1
  labels:
    ke-ingress: wzdemo-ingress
  name: wzdemo-ingress
  namespace: deftones
spec:
  rules:
  - host: cdemo.kegate-jjh.cloudappl.com
    http:
      paths:
      - backend:
          serviceName: svc-wzdemo
          servicePort: 80
        path: /
status:
  loadBalancer: {}
