apiVersion: v1
data:
  demo.conf: "{{.global.cpu.max}}/{{.idc.mem.max.test}}/{{.secret.aaabccc}}"
kind: ConfigMap
metadata:
  name: demo
  namespace: unknown

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo
  namespace: unknown
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ke-svc: demo-8905902
        wz-mv: gitText
    spec:
      containers:
        - image: 'reg.qiniu.com/unknown/repo:latest'
          imagePullPolicy: Always
          name: demo-0
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 333m
              memory: 1Gi
          volumeMounts:
            - mountPath: /go/src/demo.conf
              name: demo
              subPath: demo.conf
      volumes:
        - configMap:
            items:
              - key: demo.conf
                path: demo.conf
            name: demo
          name: demo
